### ISSUE TITLE
Axial Tilt Not Working from the Perspective of New Vessels

### ISSUE THREAD

**Issue by zingidyzongxxx** [LunaMultiplayer/TiltEm#4]
I left a comment about this on your forum thread. Basically, I'm having an issue where Kerbin will be tilted, but its axis of rotation will still be vertical. From the tracking station, everything will seem to be working correctly, but from vessels it will not work correctly. The sun will, regardless of the time of year, trace the same exact path through the sky and the axis of rotation no longer passes through the poles.

I'll try testing this some more and see if I can figure out what's causing this or if it's another mod or what.

**Comment by gavazquez** [comment]
Bear in mind that when you are in the surface (or below 80km iirc) **the skybox** is tilted, **not** the planet. So the sun and the planets are tilted and moved around instead of moving your own planet.

**Comment by zingidyzongxxx** [comment]
Why is this? It kind of breaks the mod to have it this way in my opinion.

**Comment by gavazquez** [comment]
This is how KSP works, not a mod issue. 
On stock ksp when the planet rotates the sky is rotated for simulating the day night cycle. This is like that until you reach certain altitude then the planet is rotated instead. The mod just adds the tilt axis to the calculations.

Have you tried adding a tilt of 30 degrees and going to North Pole? You should have some months with darkness and some with total daylight

**Comment by gavazquez** [comment]
Will be fixed on 1.1.0 (it's actually fixed there) altough there are some other issues
