### ISSUE TITLE
Orbit randomly changing on latest appveyor.

### ISSUE THREAD

**Issue by njbrown09** [LunaMultiplayer/TiltEm#5]
Only running stock + latest appveyor build + kopernicus.

When starting a time warp, sometimes (maybe 30% of the time) the orbit seems to randomly jump inclination and ascending node position.

**Comment by gavazquez** [comment]
Yep, that's why it's not released. I'm still fixing bugs on it as tilting the universe is not as bug free as I expected

**Comment by njbrown09** [comment]
Any update on this? Its still here.
