### ISSUE TITLE
CTD on game start with Appveyor 1.1.0.45 build

### ISSUE THREAD

**Issue by Gordon-Dry** [LunaMultiplayer/TiltEm#6]
I just wanted to test it again after I saw you commited some over the last days.

Three times in a row the game crashed immediately as soon as the first pass of config loading wants to start.

https://www.dropbox.com/s/w7g46xvygu5hzpi/2018-11-05_1%20KSP%20crashes.7z?dl=1

**Comment by Gordon-Dry** [comment]
ofc it works after removing TiltEm

**Comment by gavazquez** [comment]
Hmmm do you have the normal KSP.log (the one in the KSP folder) and the output_log?
It's usually in C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt

On my side it works fine altough it has some bugs. Also remember to install Kopernicus

**Comment by Gordon-Dry** [comment]
I added the logs to the Dropboxed archive.

**Comment by gavazquez** [comment]
Just tested on latest appveyor build and it works fine on my side with this mods:
![image](https://user-images.githubusercontent.com/12727761/48080799-d661cd80-e1ee-11e8-9a33-df1f9ca9265d.png)

You **need** to have the latest kopernicus installed for making it work, if you already have it then probably some mod is messing up with Tilt'em. The logs don't say much tbh....
